### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by enragedtadzy** [advanced-cms/advanced-reviews#174]
Hi there,

Recently installed this addon on my website and receiving the following errors on some pages, but not all... And there is no consistency between the pages receiving the error, and the ones that aren't. From what I can see at least. Hoping someone is able to help provide some insight. 

It is quite a custom solution and the error doesn't really help to point me in the right direction...

[NullReferenceException]: Object reference not set to an instance of an object.
   at EPiServer.Web.Routing.Internal.DefaultContentRoute.MatchConstraints(SegmentContext segmentContext, HttpContextBase context)
   at EPiServer.Web.Routing.Internal.DefaultUrlResolver.RouteInternal(UrlBuilder urlBuilder, ContextMode contextMode, Boolean matchContentRouteConstraints)
   at EPiServer.Web.Routing.Internal.DefaultUrlResolver.Route(UrlBuilder urlBuilder, ContextMode contextMode)
   at AdvancedExternalReviews.EditReview.ConvertEditLinksFilter.<ReplaceImages>b__3_0(Match x)
   at System.Text.RegularExpressions.RegexReplacement.Replace(MatchEvaluator evaluator, Regex regex, String input, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator)
   at System.Text.RegularExpressions.Regex.Replace(String input, String pattern, MatchEvaluator evaluator)
   at AdvancedExternalReviews.EditReview.ConvertEditLinksFilter.ReplaceImages(String html)
   at AdvancedExternalReviews.EditReview.ConvertEditLinksFilter.ReplaceHtml(String html)
   at AdvancedExternalReviews.EditReview.BufferedTextWriter.Flush(Boolean rewriteText)
   at AdvancedExternalReviews.EditReview.ConvertEditLinksFilter.OnResultExecuted(ResultExecutedContext filterContext)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_1.<BeginInvokeAction>b__1(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<>c.<BeginExecuteCore>b__152_1(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<>c.<BeginProcessRequest>b__20_1(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by barteksekula** [comment]
@enragedtadzy We have this code https://github.com/advanced-cms/advanced-reviews/blob/9e7ab116ea7296563b608d534ba5685244573047/src/external-reviews/EditReview/ConvertEditLinksFilter.cs#L33 which makes sure all images are accessible for an unauthenticated user.
Would it be possible for you to clone the repo, build locally a debug version and retry to see a better stacktrace?

**Comment by enragedtadzy** [comment]
Thanks @barteksekula for getting back to me. 

After some further consideration we have decided to drop this addon from our solution for the time being. Given our custom solution there are quite a few implications we've identified.

The error that I posted previously was caused by images hosted in the solution being referenced by the templates, and the routes for these images were not being found due to some custom routing we have created.

Another issue we came across is the use of personalization groups throughout the website (which I believe we have customized as well). When viewing components using these groups, the edit view seems to return all of them which is different to the front end view, and so it seems the controller code may not be executed in the same way.

In any case, we will revisit this later and may be in touch again.

Cheers,
Tom.

**Comment by barteksekula** [comment]
Hard to say about the images but it would be great if you could provide more info so we can adjust our code to at least not fail miserably in such scenarios.

When it comes to Visitor Groups support then it was one of the most wanted features - to be able to associate a list of Visitor Groups with a link.

It was already added in https://github.com/advanced-cms/advanced-reviews/pull/175
Will be released in v0.8.0 soon

**Comment by barteksekula** [comment]
The visitor groups has to be defined during creation of the review link. 
https://nuget.episerver.com/package/?id=Advanced.CMS.AdvancedReviews&v=0.8.0
