### ISSUE TITLE
Cannot add External review link gadget

### ISSUE THREAD

**Issue by nguyenminhvuong** [advanced-cms/advanced-reviews#192]
Hi,

I tried to add a gadget in the admin dashboard, the popup opens and says that:

"Error: could not add component"

I go to console log and see:

![image](https://user-images.githubusercontent.com/14576574/120299042-d23db400-c2f4-11eb-850b-a44890e4f08e.png)

Do you have any idea?

**Comment by barteksekula** [comment]
hi, what do you mean by admin dashboard?

**Comment by nguyenminhvuong** [comment]
I mean edit mode

**Comment by barteksekula** [comment]
Can you send the full stacktrace? There must be an exception on the server.
It works fine in Alloy and we add the gadget automatically after installing the advanced-reviews.

**Comment by nguyenminhvuong** [comment]
Yeah, I think so. It happens only on my project, Here is a full stack trace:

<html>
	<head>
		<meta name="robots" content="noindex,nofollow"><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><title>
			Page could not be loaded
		</title>
		<style type="text/css">
	        body{font-size:65%;color:black;background-color:White;}
            form{font-size:1.2em;}
	        body,table{font-family:Verdana;font-weight:normal;}
	        h1{color: gray;font-size: 1.4em;font-family:Verdana;margin:0.5em 0 0 0;}
            h2{font-size:1.2em;font-weight:bold;}
            h3{display: inline;font-weight:bold;font-size: 1.0em;}
	        .ExceptionInfo{margin:0.6em 0 0.6em 0.2em;}
	        .StackTrace{font-family:"Lucida Console";}
	        th{font-size: 0.8em;text-align:left;white-space: nowrap;}
	        td{font-size: 0.7em;}
	        .DetailedHeader{font-weight:bold;border: 1px solid black;padding:4px;text-align:center;}
	        .ReportForm{font-family:Verdana;font-weight:normal;font-size: 1.0em;color:black;}
	        .SubmitButton{font-family:Verdana;font-weight:normal;font-size: 1.0em;color:black;}
        </style>
		<script type="text/javascript">
			
		</script>
	</head><body>
		<h1 class="Title">
			Page could not be loaded

		</h1><p style="width:40em;">The link you specified does not work. This may either be the result of temporary maintenance or an incorrect link.
		</p><h2 class="DetailedHeader">Detailed error information (authorized by permissions to functions)</h2><table border="0">
	<tr>
		<th>Error occured</th><td>6/10/2021 8:12:59 AM</td>
	</tr><tr>
		<th>User IP</th><td>104.45.75.2</td>
	</tr><tr>
		<th>User Agent</th><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36</td>
	</tr><tr>
		<th>Url</th><td>https://wcm-test.ericsson.net:443/EPiServer/shell/Stores/component/</td>
	</tr><tr>
		<th>Referer</th><td><a href="https://wcm-test.ericsson.net/EPiServer/Cms/">https://wcm-test.ericsson.net/EPiServer/Cms/</a></td>
	</tr>
</table><div class="ExceptionInfo">
	<h3>Exception details: </h3> InvalidOperationException: The JSON request was too large to be deserialized.
</div><div class="ExceptionInfo">
	<h2>Stack trace:</h2><div><code><pre class="StackTrace">[InvalidOperationException: The JSON request was too large to be deserialized.]
   at System.Web.Mvc.JsonValueProviderFactory.EntryLimitedDictionary.Add(String key, Object value)
   at System.Web.Mvc.JsonValueProviderFactory.AddToBackingStore(EntryLimitedDictionary backingStore, String prefix, Object value)
   at System.Web.Mvc.JsonValueProviderFactory.AddToBackingStore(EntryLimitedDictionary backingStore, String prefix, Object value)
   at System.Web.Mvc.JsonValueProviderFactory.AddToBackingStore(EntryLimitedDictionary backingStore, String prefix, Object value)
   at System.Web.Mvc.JsonValueProviderFactory.AddToBackingStore(EntryLimitedDictionary backingStore, String prefix, Object value)
   at System.Web.Mvc.JsonValueProviderFactory.AddToBackingStore(EntryLimitedDictionary backingStore, String prefix, Object value)
   at System.Web.Mvc.JsonValueProviderFactory.GetValueProvider(ControllerContext controllerContext)
   at System.Web.Mvc.ValueProviderFactoryCollection.GetValueProvider(ControllerContext controllerContext)
   at System.Web.Mvc.ControllerBase.get_ValueProvider()
   at System.Web.Mvc.ControllerActionInvoker.GetParameterValue(ControllerContext controllerContext, ParameterDescriptor parameterDescriptor)
   at EPiServer.Shell.Services.Rest.RestControllerActionInvoker.GetParameterValue(ControllerContext controllerContext, ParameterDescriptor parameterDescriptor)
   at System.Web.Mvc.ControllerActionInvoker.GetParameterValues(ControllerContext controllerContext, ActionDescriptor actionDescriptor)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_1.<BeginInvokeAction>b__0(AsyncCallback asyncCallback, Object asyncState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.BeginInvokeAction(ControllerContext controllerContext, String actionName, AsyncCallback callback, Object state)
   at EPiServer.Shell.Services.Rest.RestControllerBase.BeginExecute(RequestContext requestContext, AsyncCallback callback, Object state)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.<>c__DisplayClass285_0.<ExecuteStepImpl>b__0()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
</pre></code></div>
</div></body></html>

**Comment by gregwiechec** [comment]
If this is dev environment try to "Reset settings" from My Settings menu. Maybe the databse is corrupted.

**Comment by barteksekula** [comment]
@nguyenminhvuong any news? Have you checked @gregwiechec suggestion? I don't see our classes in the stacktrace so I'm not sure what we can do to help you.

**Comment by nguyenminhvuong** [comment]
@barteksekula @gregwiechec thanks for your suggestion. I tried but it didn't work. But I found a solution, I added **<add key="aspnet:MaxJsonDeserializerMembers" value="150000" />** into web.config
