### ISSUE TITLE
Error while adding External Review gadget

### ISSUE THREAD

**Issue by Uvarsni** [advanced-cms/advanced-reviews#226]
We are facing issue while trying to add this gadget in CMS, it throws error as 'Could not add component'.
Kindly help us on this.

**Comment by barteksekula** [comment]
i need more info, stacktrace etc.

**Comment by machoindustries** [comment]
Hi there. I didn't report this originally, but I am also experiencing this issue. Below is the error we see in the log stream. And I attached a screenshot from Azure of the 500 error that took place after this call. Let me know if I can offer any other information.
![advancedreview-500-Microsoft-Azure](https://user-images.githubusercontent.com/36741669/216135869-1cddbf43-3d76-4e5d-b3d8-611ace78c594.png)


```
2023-02-01T18:48:32,Error,amna01mstra8s42inte,79a827,638108741124033157,0,14344,140,"EPiServer.Global : Unhandled exception in ASP.NET
System.InvalidOperationException: The JSON request was too large to be deserialized.
   at System.Web.Mvc.JsonValueProviderFactory.EntryLimitedDictionary.Add(String key, Object value)
   at System.Web.Mvc.JsonValueProviderFactory.AddToBackingStore(EntryLimitedDictionary backingStore, String prefix, Object value)
   at System.Web.Mvc.JsonValueProviderFactory.AddToBackingStore(EntryLimitedDictionary backingStore, String prefix, Object value)
   at System.Web.Mvc.JsonValueProviderFactory.AddToBackingStore(EntryLimitedDictionary backingStore, String prefix, Object value)
   at System.Web.Mvc.JsonValueProviderFactory.AddToBackingStore(EntryLimitedDictionary backingStore, String prefix, Object value)
   at System.Web.Mvc.JsonValueProviderFactory.AddToBackingStore(EntryLimitedDictionary backingStore, String prefix, Object value)
   at System.Web.Mvc.JsonValueProviderFactory.AddToBackingStore(EntryLimitedDictionary backingStore, String prefix, Object value)
   at System.Web.Mvc.JsonValueProviderFactory.AddToBackingStore(EntryLimitedDictionary backingStore, String prefix, Object value)
   at System.Web.Mvc.JsonValueProviderFactory.GetValueProvider(ControllerContext controllerContext)
   at System.Web.Mvc.ValueProviderFactoryCollection.GetValueProvider(ControllerContext controllerContext)
   at System.Web.Mvc.ControllerBase.get_ValueProvider()
   at System.Web.Mvc.ControllerActionInvoker.GetParameterValue(ControllerContext controllerContext, ParameterDescriptor parameterDescriptor)
   at EPiServer.Shell.Services.Rest.RestControllerActionInvoker.GetParameterValue(ControllerContext controllerContext, ParameterDescriptor parameterDescriptor)
   at System.Web.Mvc.ControllerActionInvoker.GetParameterValues(ControllerContext controllerContext, ActionDescriptor actionDescriptor)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_1.b__0(AsyncCallback asyncCallback, Object asyncState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.BeginInvokeAction(ControllerContext controllerContext, String actionName, AsyncCallback callback, Object state)
   at EPiServer.Shell.Services.Rest.RestControllerBase.BeginExecute(RequestContext requestContext, AsyncCallback callback, Object state)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.<>c__DisplayClass285_0.b__0()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)",
```

**Comment by barteksekula** [comment]
Are you able to add any other gadget?
