### ISSUE TITLE
Container crash

### ISSUE THREAD

**Issue by tanujatvaltech** [advanced-cms/advanced-reviews#241]
We had a major issue where all production containers crashed simultaneously. We reached out to Optimizely support and upon reviewing the error logs leading up to the crash, we found that certain calls were executed. Could you please confirm if this is a known issue and if there are any current efforts being made to address it? Our content editors use this addon on a daily basis, so we need to ensure that it is stable. Following the incident, support suggested uninstalling the addon. Can you please provide guidance on what we should do next?

VERSION; 1.3.3

`Container exited unexpectedly: last 10 seconds logs [2023-09-13T21:45:56.870813858Z    at EPiServer.Core.Internal.ProviderPipelineImplementation.GetItem(EPiServer.Core.ContentProvider, EPiServer.Core.ContentReference, EPiServer.Core.LoaderOptions)
2023-09-13T21:45:56.915555148Z    at EPiServer.Core.Internal.DefaultContentLoader.TryGet[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](EPiServer.Core.ContentReference, EPiServer.Core.LoaderOptions, System.__Canon ByRef)
2023-09-13T21:45:56.916629170Z    at Advanced.CMS.ExternalReviews.DraftContentLoader.TryGet[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](EPiServer.Core.ContentReference, EPiServer.Core.LoaderOptions, System.__Canon ByRef)
2023-09-13T21:45:56.916649970Z    at EPiServer.Core.Internal.DefaultContentRepository.TryGet[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](EPiServer.Core.ContentReference, EPiServer.Core.LoaderOptions, System.__Canon ByRef)
2023-09-13T21:45:56.916656770Z    at EPiServer.Core.Html.StringParsing.ContentFragment.GetContent(Boolean)
2023-09-13T21:45:56.916662070Z    at EPiServer.Core.Html.StringParsing.ContentFragment.GetSecurityDescriptor()
2023-09-13T21:45:56.918159700Z    at EPiServer.Core.ContentAreaItem..ctor(EPiServer.Core.Html.StringParsing.ContentFragment)
2023-09-13T21:45:56.918173800Z    at EPiServer.Core.ContentArea.CreateContentAreaItem(EPiServer.Core.Html.StringParsing.ContentFragment)
2023-09-13T21:45:56.918178600Z    at EPiServer.Core.ContentArea.b__19_0(EPiServer.Core.Html.StringParsing.ContentFragment)
2023-09-13T21:45:56.918183801Z    at System.Linq.Enumerable+SelectEnumerableIterator`2[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ToList()
2023-09-13T21:45:56.918189601Z    at EPiServer.Core.ContentArea.GetOrCreateContentAreaItemCollection(EPiServer.Core.Html.StringParsing.StringFragmentCollection)
2023-09-13T21:45:56.918194001Z    at EPiServer.Core.ContentArea.get_Fragments()
2023-09-13T21:45:56.924771532Z    at EPiServer.Core.ContentArea.get_Items()
2023-09-13T21:45:56.925415344Z    at EPiServer.SpecializedProperties.PropertyContentArea.CreateWritableClone()
2023-09-13T21:45:56.925428845Z    at EPiServer.Core.PropertyDataCollection.CreateWritableClone()
2023-09-13T21:45:56.925433045Z    at EPiServer.Core.ContentData.CreateWriteableCloneImplementation()
2023-09-13T21:45:56.925437345Z    at EPiServer.Core.PageData.CreateWriteableCloneImplementation()
2023-09-13T21:45:56.925441445Z    at EPiServer.Core.PageData.CreateWritableClone()
2023-09-13T21:45:56.925445745Z    at Advanced.CMS.ExternalReviews.ContentExtensions.AllowAccessToEveryone(EPiServer.Core.IContent)
2023-09-13T21:45:56.925450545Z    at Advanced.CMS.ExternalReviews.CustomContentLoaderInitialization.Events_LoadingContent(System.Object, EPiServer.ContentEventArgs)
2023-09-13T21:45:56.925454745Z    at EPiServer.Core.Internal.DefaultContentEvents.RaiseContentEvent(System.String, EPiServer.ContentEventArgs)
2023-09-13T21:45:56.925458945Z    at EPiServer.Core.Internal.DefaultContentLoader.TryGet[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](EPiServer.Core.ContentReference, EPiServer.Core.LoaderOptions, System.__Canon ByRef)
2023-09-13T21:45:56.925485646Z    at EPiServer.Core.Internal.DefaultContentLoader.TryGet[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Guid, EPiServer.Core.LoaderOptions, System.__Canon ByRef)
2023-09-13T21:45:56.925493546Z    at EPiServer.Core.Internal.DefaultContentLoader.TryGet[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Guid, System.Globalization.CultureInfo, System.__Canon ByRef)
2023-09-13T21:45:56.925497946Z    at Advanced.CMS.ExternalReviews.DraftContentLoader.TryGet[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Guid, System.Globalization.CultureInfo, System.__Canon ByRef)
2023-09-13T21:45:56.925503246Z    at EPiServer.Core.Internal.DefaultContentLanguageSettingsHandler.GetLogicalContentParent(EPiServer.Core.IContent)
2023-09-13T21:45:56.925507446Z    at EPiServer.Core.Internal.DefaultContentLanguageSettingsHandler.GetSetting(EPiServer.Core.ContentReference, System.Collections.Generic.HashSet`1)
2023-09-13T21:45:56.925512046Z    at EPiServer.Core.Internal.DefaultContentLanguageSettingsHandler.Get(EPiServer.Core.ContentReference, System.Collections.Generic.HashSet`1)
2023-09-13T21:45:56.925516746Z    at EPiServer.Core.Internal.DefaultContentLanguageSettingsHandler.GetSetting(EPiServer.Core.ContentReference, System.Collections.Generic.HashSet`1)
2023-09-13T21:45:56.925520946Z    at EPiServer.Core.Internal.DefaultContentLanguageSettingsHandler.Get(EPiServer.Core.ContentReference, System.Collections.Generic.HashSet`1)
2023-09-13T21:45:56.925524747Z    at EPiServer.Core.Internal.DefaultContentLanguageSettingsHandler.Get(EPiServer.Core.ContentReference, System.String)
2023-09-13T21:45:56.925528847Z    at EPiServer.Core.Internal.LanguagePipeline.Pipe(EPiServer.Core.ContentReference, EPiServer.Core.IContent, EPiServer.Core.LoaderOptions, System.Func`3)
2023-09-13T21:45:56.925532847Z    at EPiServer.Core.Internal.ProviderPipelineImplementation.GetItem(EPiServer.Core.ContentProvider, EPiServer.Core.ContentReference, EPiServer.Core.LoaderOptions)
2023-09-13T21:45:56.925536947Z    at EPiServer.Core.Internal.DefaultContentLoader.TryGet[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](EP`

**Comment by barteksekula** [comment]
Sorry it took so long, is this still an issue? Not really sure how this call can crash the server.
